import { HttpStatus } from '@nestjs/common';

/**
 * 统一错误码，用于 ErrorResponse.error.code。
 * 与 packages/contracts 的 ErrorCode 保持一致（API 内部使用本 enum）。
 */
export enum ErrorCode {
  // 通用
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  // 项目
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_SLUG_CONFLICT = 'PROJECT_SLUG_CONFLICT',
  PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',
  // 服务
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_SLUG_CONFLICT = 'SERVICE_SLUG_CONFLICT',
  // 环境
  ENVIRONMENT_NOT_FOUND = 'ENVIRONMENT_NOT_FOUND',
  ENVIRONMENT_SLUG_CONFLICT = 'ENVIRONMENT_SLUG_CONFLICT',
  // 端点
  ENDPOINT_NOT_FOUND = 'ENDPOINT_NOT_FOUND',
  ENDPOINT_RELATION_INVALID = 'ENDPOINT_RELATION_INVALID',
  ENDPOINT_CONFLICT = 'ENDPOINT_CONFLICT',
  // Manifest
  MANIFEST_INVALID = 'MANIFEST_INVALID',
  MANIFEST_VERSION_UNSUPPORTED = 'MANIFEST_VERSION_UNSUPPORTED',
  MANIFEST_APPLY_FAILED = 'MANIFEST_APPLY_FAILED',
  // 健康检查
  HEALTH_CHECK_HOST_NOT_ALLOWED = 'HEALTH_CHECK_HOST_NOT_ALLOWED',
  HEALTH_CHECK_TIMEOUT = 'HEALTH_CHECK_TIMEOUT',
  HEALTH_CHECK_FAILED = 'HEALTH_CHECK_FAILED',
  // 身份权限
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REQUIRED = 'AUTH_TOKEN_REQUIRED',
  USER_DISABLED = 'USER_DISABLED',
  PROJECT_MEMBER_NOT_FOUND = 'PROJECT_MEMBER_NOT_FOUND',
  PROJECT_MEMBER_CONFLICT = 'PROJECT_MEMBER_CONFLICT',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  // 服务凭证与审计
  SERVICE_CREDENTIAL_NOT_FOUND = 'SERVICE_CREDENTIAL_NOT_FOUND',
  SERVICE_CREDENTIAL_REVOKED = 'SERVICE_CREDENTIAL_REVOKED',
  // 可观测性
  OBSERVABILITY_LINK_NOT_FOUND = 'OBSERVABILITY_LINK_NOT_FOUND',
  // 治理记录
  GOVERNANCE_RECORD_NOT_FOUND = 'GOVERNANCE_RECORD_NOT_FOUND',
}

/** HTTP 状态码映射到通用错误码（非业务异常兜底） */
export function httpStatusToCode(status: number): ErrorCode {
  switch (status) {
    case HttpStatus.BAD_REQUEST:
      return ErrorCode.BAD_REQUEST;
    case HttpStatus.UNAUTHORIZED:
      return ErrorCode.UNAUTHORIZED;
    case HttpStatus.FORBIDDEN:
      return ErrorCode.FORBIDDEN;
    case HttpStatus.NOT_FOUND:
      return ErrorCode.NOT_FOUND;
    case HttpStatus.CONFLICT:
      return ErrorCode.CONFLICT;
    case HttpStatus.UNPROCESSABLE_ENTITY:
      return ErrorCode.VALIDATION_ERROR;
    case HttpStatus.SERVICE_UNAVAILABLE:
      return ErrorCode.SERVICE_UNAVAILABLE;
    default:
      return ErrorCode.INTERNAL_ERROR;
  }
}
